# Generated by Django 2.1 on 2018-09-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('Description', models.CharField(default='', max_length=1000)),
                ('Ingredients', models.TextField()),
                ('Instructions', models.TextField()),
                ('prep', models.CharField(default='', max_length=250)),
                ('cook', models.CharField(default='', max_length=250)),
                ('Ready_In', models.CharField(default='', max_length=250)),
                ('servings', models.CharField(default='', max_length=250)),
                ('Nutrition_Facts', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ListOfSnack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MealTypeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
            ],
        ),
    ]
