# Generated by Django 2.1 on 2018-09-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180903_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfMeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('Ingredients', models.TextField()),
                ('Instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListOfSnacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
