# Generated by Django 2.1 on 2018-09-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180906_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to=''),
        ),
    ]
