# Generated by Django 2.1 on 2018-09-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180906_2015'),
        ('api', '0004_plans_image'),
    ]

    operations = [
    ]
