# Generated by Django 2.1 on 2018-09-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20180909_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='Price',
            new_name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='Description',
        ),
    ]
