# Generated by Django 2.1 on 2018-09-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_listofmeals_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofmeals',
            name='Ready_In',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='listofmeals',
            name='cook',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='listofmeals',
            name='prep',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='listofmeals',
            name='Description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
