# Generated by Django 2.1 on 2018-09-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180909_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
