# Generated by Django 2.1 on 2018-09-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_orderplan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplan',
            name='qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
