# Generated by Django 2.1 on 2018-09-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_listofmeals_servings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOfMeals',
            new_name='ListOfMeal',
        ),
        migrations.RenameModel(
            old_name='ListOfSnacks',
            new_name='ListOfSnack',
        ),
    ]
