# Generated by Django 2.1 on 2018-09-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180904_1706'),
        ('api', '0010_auto_20180904_1707'),
    ]

    operations = [
    ]
